DROP TABLE IF EXISTS t_approvals;

CREATE TABLE IF NOT EXISTS t_approvals (
    id BIGSERIAL PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    user_id BIGSERIAL NOT NULL,
    userRole VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);