CREATE TABLE t_bookings
(
    id       BIGSERIAL PRIMARY KEY,
    event_id BIGSERIAL   NOT NULL,
    user_id  BIGSERIAL   NOT NULL,
    status   VARCHAR(50) NOT NULL,
    time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);